### ISSUE TITLE
 Getting ServerError: No LEDGER_SECRET provided 

### ISSUE THREAD

**Issue by inacali** [interledgerjs/ilp-kit#89]
Hi whilst setting up ilp kit using instructions in wiki , I am getting a  ServerError: No LEDGER_SECRET provided.  I am using npm run configure to set up the env.list . Below is the full error:

``` throw new ServerError('No ' + (prefix ? prefix.toUpperCase() + '_' : '') + 'SECRET provided.')
[ledger]     ^
[ledger] 
[ledger] ServerError: No LEDGER_SECRET provided.
[ledger]     at parseSecret (/home/shakur87/ilp-kit/node_modules/five-bells-ledger/node_modules/five-bells-shared/lib/config.js:109:11)
[ledger]     at Object.generateSecret (/home/shakur87/ilp-kit/node_modules/five-bells-ledger/node_modules/five-bells-shared/lib/config.js:99:18)
[ledger]     at loadConfig (/home/shakur87/ilp-kit/node_modules/five-bells-ledger/src/lib/config.js:99:40)
[ledger]     at Object.<anonymous> (/home/shakur87/ilp-kit/node_modules/five-bells-ledger/src/services/config.js:5:18)
[ledger]     at Module._compile (module.js:570:32)
[ledger]     at Object.Module._extensions..js (module.js:579:10)
[ledger]     at Module.load (module.js:487:32)
[ledger]     at tryModuleLoad (module.js:446:12)
[ledger]     at Function.Module._load (module.js:438:3)
[ledger]     at Module.require (module.js:497:17)
[ledger]     at require (internal/module.js:20:19)
[ledger]     at Object.<anonymous> (/home/shakur87/ilp-kit/node_modules/five-bells-ledger/src/models/accounts.js:4:16)
[ledger]     at Module._compile (module.js:570:32)
[ledger]     at Object.Module._extensions..js (module.js:579:10)
[ledger]     at Module.load (module.js:487:32)
[ledger]     at tryModuleLoad (module.js:446:12)
 ```

**Comment by vhpoet** [comment]
@inacali should be working now.

**Comment by inacali** [comment]
Thanks @vhpoet its fixed that error, but now I seem to be getting another error whilst the db is syncing 
not sure if I have setup the db correctly are the instructions on the setup page up to date?
 
```
[ledger] 2016-11-30T11:02:10.381Z ledger:app info database sync aborted
[ledger] 2016-11-30T11:02:10.463Z ledger:app error error: select * from "L_LU_REJECTION_REASON" - relation "L_LU_REJECTION_REASON" does not exist
[ledger]     at Connection.parseE (/home/shakur87/ilp-kit/node_modules/pg/lib/connection.js:539:11)
[ledger]     at Connection.parseMessage (/home/shakur87/ilp-kit/node_modules/pg/lib/connection.js:366:17)
[ledger]     at Socket.<anonymous> (/home/shakur87/ilp-kit/node_modules/pg/lib/connection.js:105:22)
[ledger]     at emitOne (events.js:96:13)
[ledger]     at Socket.emit (events.js:188:7)
[ledger]     at readableAddChunk (_stream_readable.js:176:18)
[ledger]     at Socket.Readable.push (_stream_readable.js:134:10)
[ledger]     at TCP.onread (net.js:548:20)

**Comment by misnuge** [comment]
117th line of db.js(ilp-kit/node_modules/five-bells-ledger/src/lib/db.js) should be modified like below.

const command = path.resolve(__dirname, '../../node_modules/pg-migrator/bin/pg-migrator')

If not, db schema won't be synced.


________________________________
보낸 사람: inacali <notifications@github.com>
보낸 날짜: 2016년 11월 30일 수요일 오후 8:15:31
받는 사람: interledgerjs/ilp-kit
제목: Re: [interledgerjs/ilp-kit] Getting ServerError: No LEDGER_SECRET provided (#89)


Thanks @vhpoet<https://github.com/vhpoet> its fixed that error, but now I seem to be getting another error whilst the db is syncing
not sure if I have setup the db correctly are the instructions on the setup page up to date?

[ledger] 2016-11-30T11:02:10.381Z ledger:app info database sync aborted
[ledger] 2016-11-30T11:02:10.463Z ledger:app error error: select * from "L_LU_REJECTION_REASON" - relation "L_LU_REJECTION_REASON" does not exist
[ledger]     at Connection.parseE (/home/shakur87/ilp-kit/node_modules/pg/lib/connection.js:539:11)
[ledger]     at Connection.parseMessage (/home/shakur87/ilp-kit/node_modules/pg/lib/connection.js:366:17)
[ledger]     at Socket.<anonymous> (/home/shakur87/ilp-kit/node_modules/pg/lib/connection.js:105:22)
[ledger]     at emitOne (events.js:96:13)
[ledger]     at Socket.emit (events.js:188:7)
[ledger]     at readableAddChunk (_stream_readable.js:176:18)
[ledger]     at Socket.Readable.push (_stream_readable.js:134:10)
[ledger]     at TCP.onread (net.js:548:20)


-

**Comment by inacali** [comment]
thanks @misnuge I tried that,  it didn't work unfortunately still getting the same error

**Comment by vhpoet** [comment]
@inacali please try with the latest version, should be working now. If it doesn't, remove `node_modules` and install it again.

**Comment by inacali** [comment]
@vhpoet Yep that got it working
